/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LuftiLoading {}
  interface LuftiLoadingAttributes extends StencilHTMLAttributes {}

  interface LuftiMain {}
  interface LuftiMainAttributes extends StencilHTMLAttributes {}

  interface LuftiSearch {}
  interface LuftiSearchAttributes extends StencilHTMLAttributes {
    'onIsLoading'?: (event: CustomEvent<boolean>) => void;
    'onLuftiID'?: (event: CustomEvent<string>) => void;
    'onLuftiIDSelected'?: (event: CustomEvent<{}>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LuftiLoading': Components.LuftiLoading;
    'LuftiMain': Components.LuftiMain;
    'LuftiSearch': Components.LuftiSearch;
  }

  interface StencilIntrinsicElements {
    'lufti-loading': Components.LuftiLoadingAttributes;
    'lufti-main': Components.LuftiMainAttributes;
    'lufti-search': Components.LuftiSearchAttributes;
  }


  interface HTMLLuftiLoadingElement extends Components.LuftiLoading, HTMLStencilElement {}
  var HTMLLuftiLoadingElement: {
    prototype: HTMLLuftiLoadingElement;
    new (): HTMLLuftiLoadingElement;
  };

  interface HTMLLuftiMainElement extends Components.LuftiMain, HTMLStencilElement {}
  var HTMLLuftiMainElement: {
    prototype: HTMLLuftiMainElement;
    new (): HTMLLuftiMainElement;
  };

  interface HTMLLuftiSearchElement extends Components.LuftiSearch, HTMLStencilElement {}
  var HTMLLuftiSearchElement: {
    prototype: HTMLLuftiSearchElement;
    new (): HTMLLuftiSearchElement;
  };

  interface HTMLElementTagNameMap {
    'lufti-loading': HTMLLuftiLoadingElement
    'lufti-main': HTMLLuftiMainElement
    'lufti-search': HTMLLuftiSearchElement
  }

  interface ElementTagNameMap {
    'lufti-loading': HTMLLuftiLoadingElement;
    'lufti-main': HTMLLuftiMainElement;
    'lufti-search': HTMLLuftiSearchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
