/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface LuftiLoading {}
  interface LuftiLoadingAttributes extends StencilHTMLAttributes {}

  interface LuftiMain {}
  interface LuftiMainAttributes extends StencilHTMLAttributes {}

  interface LuftiSearch {}
  interface LuftiSearchAttributes extends StencilHTMLAttributes {
    'onIsLoading'?: (event: CustomEvent<boolean>) => void;
    'onLuftiID'?: (event: CustomEvent<string>) => void;
    'onLuftiIDSelected'?: (event: CustomEvent<{}>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'LuftiLoading': Components.LuftiLoading;
    'LuftiMain': Components.LuftiMain;
    'LuftiSearch': Components.LuftiSearch;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'lufti-loading': Components.LuftiLoadingAttributes;
    'lufti-main': Components.LuftiMainAttributes;
    'lufti-search': Components.LuftiSearchAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLLuftiLoadingElement extends Components.LuftiLoading, HTMLStencilElement {}
  var HTMLLuftiLoadingElement: {
    prototype: HTMLLuftiLoadingElement;
    new (): HTMLLuftiLoadingElement;
  };

  interface HTMLLuftiMainElement extends Components.LuftiMain, HTMLStencilElement {}
  var HTMLLuftiMainElement: {
    prototype: HTMLLuftiMainElement;
    new (): HTMLLuftiMainElement;
  };

  interface HTMLLuftiSearchElement extends Components.LuftiSearch, HTMLStencilElement {}
  var HTMLLuftiSearchElement: {
    prototype: HTMLLuftiSearchElement;
    new (): HTMLLuftiSearchElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'lufti-loading': HTMLLuftiLoadingElement
    'lufti-main': HTMLLuftiMainElement
    'lufti-search': HTMLLuftiSearchElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'lufti-loading': HTMLLuftiLoadingElement;
    'lufti-main': HTMLLuftiMainElement;
    'lufti-search': HTMLLuftiSearchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
