/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Luftdaten,
} from './models/luftdaten/luftdaten';

export namespace Components {
  interface LuftiFace {
    'mood': number;
  }
  interface LuftiFaceSlider {}
  interface LuftiLegend {}
  interface LuftiLoading {}
  interface LuftiMain {}
  interface LuftiReverseGeo {
    'location': { latitude: string, longitude: string };
  }
  interface LuftiSearch {}
}

declare global {


  interface HTMLLuftiFaceElement extends Components.LuftiFace, HTMLStencilElement {}
  var HTMLLuftiFaceElement: {
    prototype: HTMLLuftiFaceElement;
    new (): HTMLLuftiFaceElement;
  };

  interface HTMLLuftiFaceSliderElement extends Components.LuftiFaceSlider, HTMLStencilElement {}
  var HTMLLuftiFaceSliderElement: {
    prototype: HTMLLuftiFaceSliderElement;
    new (): HTMLLuftiFaceSliderElement;
  };

  interface HTMLLuftiLegendElement extends Components.LuftiLegend, HTMLStencilElement {}
  var HTMLLuftiLegendElement: {
    prototype: HTMLLuftiLegendElement;
    new (): HTMLLuftiLegendElement;
  };

  interface HTMLLuftiLoadingElement extends Components.LuftiLoading, HTMLStencilElement {}
  var HTMLLuftiLoadingElement: {
    prototype: HTMLLuftiLoadingElement;
    new (): HTMLLuftiLoadingElement;
  };

  interface HTMLLuftiMainElement extends Components.LuftiMain, HTMLStencilElement {}
  var HTMLLuftiMainElement: {
    prototype: HTMLLuftiMainElement;
    new (): HTMLLuftiMainElement;
  };

  interface HTMLLuftiReverseGeoElement extends Components.LuftiReverseGeo, HTMLStencilElement {}
  var HTMLLuftiReverseGeoElement: {
    prototype: HTMLLuftiReverseGeoElement;
    new (): HTMLLuftiReverseGeoElement;
  };

  interface HTMLLuftiSearchElement extends Components.LuftiSearch, HTMLStencilElement {}
  var HTMLLuftiSearchElement: {
    prototype: HTMLLuftiSearchElement;
    new (): HTMLLuftiSearchElement;
  };
  interface HTMLElementTagNameMap {
    'lufti-face': HTMLLuftiFaceElement;
    'lufti-face-slider': HTMLLuftiFaceSliderElement;
    'lufti-legend': HTMLLuftiLegendElement;
    'lufti-loading': HTMLLuftiLoadingElement;
    'lufti-main': HTMLLuftiMainElement;
    'lufti-reverse-geo': HTMLLuftiReverseGeoElement;
    'lufti-search': HTMLLuftiSearchElement;
  }
}

declare namespace LocalJSX {
  interface LuftiFace {
    'mood'?: number;
  }
  interface LuftiFaceSlider {}
  interface LuftiLegend {}
  interface LuftiLoading {}
  interface LuftiMain {}
  interface LuftiReverseGeo {
    'location'?: { latitude: string, longitude: string };
  }
  interface LuftiSearch {
    'onIsLoading'?: (event: CustomEvent<boolean>) => void;
    'onLuftdaten'?: (event: CustomEvent<Luftdaten>) => void;
    'onLuftiID'?: (event: CustomEvent<string>) => void;
  }

  interface IntrinsicElements {
    'lufti-face': LuftiFace;
    'lufti-face-slider': LuftiFaceSlider;
    'lufti-legend': LuftiLegend;
    'lufti-loading': LuftiLoading;
    'lufti-main': LuftiMain;
    'lufti-reverse-geo': LuftiReverseGeo;
    'lufti-search': LuftiSearch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lufti-face': LocalJSX.LuftiFace & JSXBase.HTMLAttributes<HTMLLuftiFaceElement>;
      'lufti-face-slider': LocalJSX.LuftiFaceSlider & JSXBase.HTMLAttributes<HTMLLuftiFaceSliderElement>;
      'lufti-legend': LocalJSX.LuftiLegend & JSXBase.HTMLAttributes<HTMLLuftiLegendElement>;
      'lufti-loading': LocalJSX.LuftiLoading & JSXBase.HTMLAttributes<HTMLLuftiLoadingElement>;
      'lufti-main': LocalJSX.LuftiMain & JSXBase.HTMLAttributes<HTMLLuftiMainElement>;
      'lufti-reverse-geo': LocalJSX.LuftiReverseGeo & JSXBase.HTMLAttributes<HTMLLuftiReverseGeoElement>;
      'lufti-search': LocalJSX.LuftiSearch & JSXBase.HTMLAttributes<HTMLLuftiSearchElement>;
    }
  }
}


